import React from 'react';
import { Link } from 'react-router-dom';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0B1220] text-gray-300">
      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
            <p className="text-sm text-gray-500 mt-1">Last updated: February 26, 2026</p>
          </div>
          <Link to="/" className="text-sm text-blue-400 hover:text-blue-300 transition">
            Back to Dashboard
          </Link>
        </div>

        <div className="space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using AuditGraph ("Service"), operated by NexgenixLabs ("Company"),
              you agree to be bound by these Terms of Service. If you are using the Service on behalf
              of an organization, you represent that you have authority to bind that organization.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Service Description</h2>
            <p>
              AuditGraph is an identity risk management platform that connects to your cloud environments
              (Azure, AWS, GCP) to discover, analyze, and report on identity security posture. The Service
              includes identity discovery, risk scoring, compliance monitoring, remediation guidance,
              access reviews, and audit reporting.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. Account Plans & Billing</h2>
            <h3 className="text-sm font-semibold text-gray-200 mt-4 mb-2">3.1 Plans</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Free:</strong> 1 active subscription, 50 identities, limited features</li>
              <li><strong>Trial:</strong> 5 active subscriptions, 500 identities, 14-day duration</li>
              <li><strong>Pro:</strong> $200/month platform fee + $69/subscription/month (Azure), unlimited identities</li>
              <li><strong>Enterprise:</strong> Custom pricing with commitment discounts (15-35% for 1-5 year terms)</li>
            </ul>

            <h3 className="text-sm font-semibold text-gray-200 mt-4 mb-2">3.2 Billing</h3>
            <p>
              Pro and Enterprise plans are billed monthly in arrears. Invoices are generated at the
              start of each billing period and are due within 30 days (configurable). Payment terms,
              tax rates, and billing addresses are managed in Settings.
            </p>

            <h3 className="text-sm font-semibold text-gray-200 mt-4 mb-2">3.3 Subscription Activation</h3>
            <p>
              Cloud subscriptions discovered during scans start in "discovered" status. You activate
              subscriptions for monitoring at your discretion. Only active subscriptions incur billing
              charges.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. User Responsibilities</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Maintain the security of your account credentials and API keys</li>
              <li>Provide accurate and current organization and billing information</li>
              <li>Ensure cloud provider credentials have appropriate read-only permissions</li>
              <li>Comply with your cloud providers' terms of service</li>
              <li>Not use the Service for unauthorized security testing of third-party systems</li>
              <li>Not attempt to circumvent tenant isolation or access other tenants' data</li>
              <li>Not reverse-engineer, decompile, or attempt to derive the source code</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Data Ownership</h2>
            <p>
              You retain all ownership rights to your cloud environment data. We process this data
              solely to provide the Service. Discovery results, risk assessments, and compliance reports
              generated by the Service are derivative works based on your data and are owned by you.
              You may export all data at any time via the Evidence Center.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Service Level Agreement</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Availability:</strong> 99.9% uptime target (excluding scheduled maintenance)</li>
              <li><strong>API Latency:</strong> P95 response time under 500ms</li>
              <li><strong>Scan Success Rate:</strong> 95% target for discovery scans</li>
              <li><strong>Support:</strong> Email support for all plans; priority support for Enterprise</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p>
              The Service provides security analysis and recommendations but does not guarantee
              prevention of security incidents. AuditGraph is a diagnostic tool, not a security control.
              You remain responsible for implementing remediation actions and maintaining your cloud
              security posture. Our total liability shall not exceed the fees paid in the 12 months
              preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Termination</h2>
            <p>
              Either party may terminate the agreement with 30 days written notice. Upon termination,
              we will provide a final data export opportunity and then permanently delete all tenant
              data within 30 days. Prepaid commitment terms are non-refundable after the first 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Changes to Terms</h2>
            <p>
              We may update these terms with 30 days advance notice via email and in-app notification.
              Continued use after changes take effect constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Contact</h2>
            <p>
              For questions about these terms, contact{' '}
              <span className="text-blue-400">legal@nexgenixlabs.com</span>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
