import React, { useState, useMemo } from 'react';
import {
  type IdentityDetailsResponse,
  type RoleIntelligence,
  type TabId,
  riskBadge,
  DataSource,
} from './types';
// Role usage primitives are the canonical source for all usage display.
// Every tab uses the same normalization + badge logic. Do not inline.
import { normalizeRoleKey, getRoleUsageBadge, type RoleUsageEntry } from '../../utils/roleUtils';
import { getBreachInfo } from '../../constants/breachExamples';

interface RolesTabProps {
  identity: IdentityDetailsResponse['identity'];
  data: IdentityDetailsResponse;
  groupedRoles: { azure: any[]; entra: any[] };
  intelByRole: Record<string, RoleIntelligence>;
  setActiveTab: (tab: TabId) => void;
}

function usageNoteFor(roleName: string, roleUsage?: Record<string, RoleUsageEntry>): string {
  if (!roleUsage) return 'unknown';
  const entry = roleUsage[normalizeRoleKey(roleName)];
  if (!entry) return 'no inference data';
  return entry.used ? `used (${entry.confidence})` : 'no evidence';
}

function generateCleanupScript(identityName: string, roles: any[], roleUsage?: Record<string, RoleUsageEntry>): string {
  const removable = roles.filter((r: any) => r.is_removable);
  if (removable.length === 0) return '# No removable roles found';

  const lines = [
    `# Cleanup Script for: ${identityName}`,
    `# Generated: ${new Date().toISOString()}`,
    `# Removable roles: ${removable.length}`,
    '',
    '# REVIEW EACH REMOVAL CAREFULLY before executing',
    '',
  ];

  for (const r of removable) {
    const roleType = r.role_type || 'azure';
    const usageNote = usageNoteFor(r.role_name, roleUsage);
    lines.push(`# Role: ${r.role_name} (${roleType}) — Usage: ${usageNote}`);

    if (roleType === 'entra') {
      lines.push(`# Remove Entra directory role assignment`);
      lines.push(`Remove-AzureADDirectoryRoleMember -ObjectId "<RoleObjectId>" -MemberId "<IdentityObjectId>"`);
    } else {
      lines.push(`# Remove Azure RBAC role assignment`);
      lines.push(`Remove-AzRoleAssignment -SignInName "${identityName}" -RoleDefinitionName "${r.role_name}" -Scope "${r.scope || '/'}"`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateRoleScript(identityName: string, identityId: string, r: any, roleUsage?: Record<string, RoleUsageEntry>): string {
  const roleType = r.role_type || 'azure';
  const usageNote = usageNoteFor(r.role_name, roleUsage);
  if (roleType === 'entra') {
    return `# Remove Entra directory role: ${r.role_name}
# Identity: ${identityName} (${identityId})
# Usage: ${usageNote}
# Generated by AuditGraph

Connect-MgGraph -Scopes "RoleManagement.ReadWrite.Directory"

$directoryRole = Get-MgDirectoryRole | Where-Object {$_.DisplayName -eq "${r.role_name}"}

Remove-MgDirectoryRoleMemberByRef \`
  -DirectoryRoleId $directoryRole.Id \`
  -DirectoryObjectId "${identityId}"

Write-Host "Removed ${r.role_name} from ${identityName}" -ForegroundColor Green
Write-Host "Run a new AuditGraph scan to verify."`;
  }
  return `# Remove Azure RBAC role: ${r.role_name}
# Identity: ${identityName} (${identityId})
# Scope: ${r.scope || '<SCOPE>'}
# Usage: ${usageNote}
# Generated by AuditGraph

Connect-AzAccount

Remove-AzRoleAssignment \`
  -ObjectId "${identityId}" \`
  -RoleDefinitionName "${r.role_name}" \`
  -Scope "${r.scope || '<SCOPE>'}"

Write-Host "Removed ${r.role_name} from ${identityName}" -ForegroundColor Green
Write-Host "Run a new AuditGraph scan to verify."`;
}

function RoleCard({ r, intel, setActiveTab, identityName, identityId, onShowScript, roleUsage }: {
  r: any; intel?: RoleIntelligence; setActiveTab: (tab: TabId) => void;
  identityName: string; identityId: string; onShowScript: (script: string) => void;
  roleUsage?: Record<string, RoleUsageEntry>;
}) {
  return (
    <div className={`border rounded-xl p-4 ${r.is_removable ? 'border-orange-200 bg-orange-50/30' : ''}`}>
      <div className="flex items-center justify-between gap-2">
        <div className="font-semibold text-gray-900 text-sm">{r.role_name}</div>
        <div className="flex items-center gap-1">
          {r.is_removable && (
            <button
              onClick={() => onShowScript(generateRoleScript(identityName, identityId, r, roleUsage))}
              className="px-1.5 py-0.5 rounded text-[10px] font-mono font-semibold bg-slate-100 text-slate-600 hover:bg-slate-200 transition border border-slate-200"
              title="Preview PowerShell removal script"
            >
              PS1
            </button>
          )}
          {getRoleUsageBadge(r.role_name || r.display_name || r.name, roleUsage)}
          {riskBadge(r.risk_level)}
        </div>
      </div>
      <div className="text-xs text-gray-500 mt-1 break-all">{r.scope}</div>
      <div className="flex flex-wrap items-center gap-2 mt-2 text-xs text-gray-500">
        {r.days_since_assigned != null && (
          <span>Assigned {r.days_since_assigned}d ago</span>
        )}
        {r.resource_type && <span>· {r.resource_type}</span>}
        {!r.scope_exists && <span className="text-red-600">· Resource deleted</span>}
        {r.redundant_with && <span className="text-yellow-600">· Redundant with {r.redundant_with}</span>}
      </div>
      {r.is_removable && (
        <div className="mt-2 flex items-center gap-1 text-xs text-orange-700">
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
          </svg>
          Candidate for removal
        </div>
      )}
      {r.why_critical && (() => {
        const breach = getBreachInfo(r.role_name || r.display_name || r.name || '');
        const isRecentlyActive = r.why_critical &&
          !r.why_critical.includes('never signed in') &&
          !r.why_critical.includes('is disabled') &&
          !r.why_critical.includes('expired') &&
          !r.why_critical.includes('dormant') &&
          !r.why_critical.includes('stale');
        return (
          <div className="mt-2 space-y-0 rounded overflow-hidden">
            <div className="text-xs text-gray-700 bg-red-50 p-2">{r.why_critical}</div>
            {breach && !isRecentlyActive ? (
              <>
                <div className="text-[11px] text-amber-800 bg-amber-50/60 border-l-2 border-amber-400 px-2 py-1.5">
                  <span className="font-semibold">Real-world precedent:</span> {breach.breach}
                </div>
                <div className="text-[11px] text-red-800 bg-red-50/60 border-l-2 border-red-400 px-2 py-1.5">
                  <span className="font-semibold">Penalty exposure:</span> {breach.penalty}
                </div>
              </>
            ) : isRecentlyActive ? (
              <div className="text-[11px] text-emerald-700 bg-emerald-50/60 border-l-2 border-emerald-400 px-2 py-1.5">
                Recently active — monitor for anomalous behavior
              </div>
            ) : null}
          </div>
        );
      })()}
      {intel && (
        <div className="flex items-center gap-2 mt-2">
          {intel.attack_patterns.length > 0 && (
            <button onClick={() => setActiveTab('compliance')} className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-red-50 text-red-700 hover:bg-red-100 transition">
              {intel.attack_patterns.length} incident{intel.attack_patterns.length > 1 ? 's' : ''}
            </button>
          )}
          {intel.hipaa_violations.length > 0 && (
            <button onClick={() => setActiveTab('compliance')} className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-purple-50 text-purple-700 hover:bg-purple-100 transition">
              {intel.hipaa_violations.length} HIPAA
            </button>
          )}
        </div>
      )}
    </div>
  );
}

export function RolesTab({ identity, data, groupedRoles, intelByRole, setActiveTab }: RolesTabProps) {
  const [copied, setCopied] = useState(false);
  const [roleScript, setRoleScript] = useState<string | null>(null);
  const [roleScriptCopied, setRoleScriptCopied] = useState(false);

  const roleUsage = (data as any)?.role_usage as Record<string, RoleUsageEntry> | undefined;
  const allRoles = useMemo(() => [...groupedRoles.azure, ...groupedRoles.entra], [groupedRoles]);
  const removableCount = useMemo(() => allRoles.filter((r: any) => r.is_removable).length, [allRoles]);

  // Count roles with no usage evidence (from canonical inference)
  const rolesWithNoEvidence = useMemo(() => {
    if (!roleUsage) return [];
    return allRoles.filter((r: any) => {
      const name = r.role_name || r.display_name || r.name || '';
      const usage = roleUsage[normalizeRoleKey(name)];
      return !usage?.used;
    });
  }, [allRoles, roleUsage]);

  const handleCopyScript = () => {
    const script = generateCleanupScript(identity.display_name || '', allRoles, roleUsage);
    navigator.clipboard.writeText(script);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div>
      <DataSource label="Azure Resource Manager + Microsoft Graph API" apiSource="/roleAssignments, /roleManagement/directory" collectedAt={data?.evidence?.collected_at} />

      {/* Role usage inference banner */}
      {roleUsage && rolesWithNoEvidence.length > 0 && (
        <div className="mt-3 bg-amber-50 border border-amber-200 rounded-xl px-4 py-3">
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span className="text-sm font-medium text-amber-800">
              {rolesWithNoEvidence.length} role{rolesWithNoEvidence.length > 1 ? 's' : ''} with no usage evidence — review for removal
            </span>
          </div>
        </div>
      )}
      {roleUsage && rolesWithNoEvidence.length === 0 && allRoles.length > 0 && (
        <div className="mt-3 bg-green-50 border border-green-200 rounded-xl px-4 py-3">
          <div className="flex items-center gap-2">
            <svg className="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            <span className="text-sm font-medium text-green-800">
              All roles have usage evidence (inferred from activity signals)
            </span>
          </div>
        </div>
      )}

      {/* Removable roles banner */}
      {removableCount > 0 && (
        <div className="mt-3 flex items-center justify-between bg-orange-50 border border-orange-200 rounded-xl px-4 py-3">
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
            </svg>
            <span className="text-sm font-medium text-orange-800">
              {removableCount} role{removableCount > 1 ? 's' : ''} can be safely removed
            </span>
            <span className="text-xs text-orange-600">
              (stale, dormant, or never used)
            </span>
          </div>
          <button
            onClick={handleCopyScript}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg bg-orange-100 text-orange-800 hover:bg-orange-200 transition"
          >
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
            </svg>
            {copied ? 'Copied!' : 'Copy Cleanup Script'}
          </button>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-3">
        {/* Azure RBAC */}
        <div>
          <div className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
            Azure RBAC Roles
            <span className="px-2 py-0.5 rounded-full text-xs bg-blue-100 text-blue-700">
              {groupedRoles.azure.length}
            </span>
            {groupedRoles.azure.filter((r: any) => r.is_removable).length > 0 && (
              <span className="px-2 py-0.5 rounded-full text-xs bg-orange-100 text-orange-700">
                {groupedRoles.azure.filter((r: any) => r.is_removable).length} removable
              </span>
            )}
          </div>
          {groupedRoles.azure.length === 0 ? (
            <div className="text-sm text-gray-500 bg-gray-50 rounded-xl p-4">No Azure RBAC roles assigned.</div>
          ) : (
            <div className="space-y-2">
              {groupedRoles.azure.map((r: any, idx: number) => (
                <RoleCard key={idx} r={r} intel={intelByRole[r.role_name]} setActiveTab={setActiveTab}
                  identityName={identity.display_name || ''} identityId={identity.identity_id || ''}
                  onShowScript={setRoleScript} roleUsage={roleUsage} />
              ))}
            </div>
          )}
        </div>

        {/* Entra Directory Roles */}
        <div>
          <div className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
            Entra Directory Roles
            <span className="px-2 py-0.5 rounded-full text-xs bg-indigo-100 text-indigo-700">
              {groupedRoles.entra.length}
            </span>
            {groupedRoles.entra.filter((r: any) => r.is_removable).length > 0 && (
              <span className="px-2 py-0.5 rounded-full text-xs bg-orange-100 text-orange-700">
                {groupedRoles.entra.filter((r: any) => r.is_removable).length} removable
              </span>
            )}
          </div>
          {groupedRoles.entra.length === 0 ? (
            <div className="text-sm text-gray-500 bg-gray-50 rounded-xl p-4">No Entra directory roles assigned.</div>
          ) : (
            <div className="space-y-2">
              {groupedRoles.entra.map((r: any, idx: number) => (
                <RoleCard key={idx} r={r} intel={intelByRole[r.role_name]} setActiveTab={setActiveTab}
                  identityName={identity.display_name || ''} identityId={identity.identity_id || ''}
                  onShowScript={setRoleScript} roleUsage={roleUsage} />
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Per-role script modal */}
      {roleScript && (
        <div className="fixed inset-0 z-50 flex items-center justify-center" style={{ backdropFilter: 'blur(4px)' }}>
          <div className="absolute inset-0 bg-black/50" onClick={() => { setRoleScript(null); setRoleScriptCopied(false); }} />
          <div className="relative w-full max-w-xl rounded-xl shadow-2xl flex flex-col" style={{ backgroundColor: '#1E293B', border: '1px solid rgba(255,255,255,0.1)', maxHeight: '70vh' }}>
            <div className="flex items-center justify-between p-4" style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
              <div className="text-sm font-semibold" style={{ color: '#F1F5F9' }}>Role Removal Script</div>
              <button onClick={() => { setRoleScript(null); setRoleScriptCopied(false); }} style={{ background: 'none', border: 'none', color: '#94A3B8', cursor: 'pointer', fontSize: 18 }}>✕</button>
            </div>
            <pre className="flex-1 overflow-auto m-0 px-5 py-4 text-xs leading-relaxed" style={{ backgroundColor: '#0F172A', color: '#7DD3FC', fontFamily: 'Courier New, monospace', whiteSpace: 'pre', minHeight: 200 }}>
              {roleScript}
            </pre>
            <div className="flex justify-end gap-2 p-3" style={{ borderTop: '1px solid rgba(255,255,255,0.08)' }}>
              <button
                onClick={() => { navigator.clipboard.writeText(roleScript); setRoleScriptCopied(true); setTimeout(() => setRoleScriptCopied(false), 2000); }}
                className="px-4 py-2 rounded-md text-xs font-medium"
                style={{ background: roleScriptCopied ? 'rgba(22,163,74,0.2)' : 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', color: roleScriptCopied ? '#86EFAC' : '#E2E8F0', cursor: 'pointer' }}
              >
                {roleScriptCopied ? '✓ Copied!' : 'Copy to Clipboard'}
              </button>
              <button
                onClick={() => {
                  const blob = new Blob([roleScript], { type: 'text/plain' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a'); a.href = url; a.download = 'auditgraph-role-removal.ps1';
                  a.click(); URL.revokeObjectURL(url);
                }}
                className="px-4 py-2 rounded-md text-xs font-medium"
                style={{ background: 'rgba(37,99,235,0.2)', border: '1px solid rgba(37,99,235,0.4)', color: '#93C5FD', cursor: 'pointer' }}
              >
                Download .ps1
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
